# Application Settings Configuration File
# Note the use of double percentage signs (%%) to escape percentage signs in INI files.

[Folders]
csv_dir = ./data/
plot_dir = ./data/plots/
dest_dir = ./data/
staging_dir = ./data/staging/
archive_dir = ./data/archive/
filename_format = %%Y%%m%%d-%%H%%M%%S

[Stocks]
tickers = META, AAPL, AMZN, NFLX, GOOG
period = 5d
interval = 1h

[Logging]
log_active = 1
log_path = ./logs/
log_level = DEBUG
log_format = %%(asctime)s-%%(name)s-%%(levelname)s:%%(message)s
log_silence_list = yfinance, peewee, urllib3, matplotlib
 