name: Download and Plot FAANG Data

on:
  schedule:
    - cron: "0 13 * * *"   # daily @13:00 UTC 
  workflow_dispatch:        # manual start button

permissions:
  contents: write   # Needed to fix 403 Errors when Commiting to Repo

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'   # my version

      # 3. Install dependencies (if you have requirements.txt)
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      # 4. Run your script
      - name: Run Python Script
        run: python faang.py

      - name: Show files
        run: |
          pwd
          find . -type f

      # 5. Add/Commit/Push archived logs, CSVs and images to Repo
      - name: Commit generated outputs to repo
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add logs/*.log data/*.csv data/archive/*.csv data/plots/*.png || true

          git status
          git commit -m "Added generated csv/png/log outputs [skip ci]" || echo "Nothing to commit"
          git push

      # 6. Upload logs, CSVs and images as artifacts
      - name: Upload output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: script-output
          path: |
            logs/*.log
            data/plots/*.png
            data/*.csv
          if-no-files-found: warn

